version: '3.3'
services:
  api:
    container_name: api
    image: shortner_api
    build: .
    tty: true
    stdin_open: true
    env_file: .env
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app:cached
      - bundle_cache:/bundle:cached
    ports:
      - "3000:3000"
    external_links:
      - db
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12.5
    env_file:
      .env
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
volumes:
  bundle_cache:
